"""
Train a Transformers causal-LM model from user feedback-derived datasets.

- Consumes the JSONL files generated by backend.utils.finetune_from_feedback.build_all_feedback_datasets
  (feedback_summarization.jsonl and feedback_qa.jsonl).
- Tokenizes with the student tokenizer if available, otherwise falls back to the teacher tokenizer.
- Fine-tunes the teacher (HF) model for a short run and saves the resulting checkpoint.

This script is intentionally simple and CPU-friendly by default (small batch/epochs). For real training, 
run on GPU and adjust hyperparameters accordingly.
"""
from __future__ import annotations
import os
import json
from dataclasses import dataclass
from typing import List, Dict, Any, Optional, Tuple


# Lazy heavy imports inside functions where possible

from backend.utils.finetune_from_feedback import build_all_feedback_datasets

# Default model/tokenizer locations in this repo
STUDENT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models", "student_model")
TEACHER_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models", "teacher_model")
DEFAULT_OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models", "teacher_model_finetuned_feedback")


@dataclass
class TrainConfig:
    epochs: int = 1
    lr: float = 5e-6
    batch_size: int = 1
    gradient_accumulation_steps: int = 1
    max_length: int = 1024
    max_prompt_length: int = 512
    save_steps: int = 0  # disable by default
    logging_steps: int = 10
    seed: int = 42


@dataclass
class Paths:
    summarization_jsonl: Optional[str]
    qa_jsonl: Optional[str]
    output_dir: str


def _load_jsonl(path: str) -> List[Dict[str, Any]]:
    items: List[Dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                items.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return items


def _prepare_pairs(sum_path: Optional[str], qa_path: Optional[str]) -> List[Tuple[str, str]]:
    """
    Normalize examples into (prompt, target) pairs for causal LM training.
    - Summarization: prompt = "summarize: {source_text}", target = target_summary
    - QA:            prompt = "question: {question}", target = answer
    """
    pairs: List[Tuple[str, str]] = []
    if sum_path and os.path.exists(sum_path):
        for ex in _load_jsonl(sum_path):
            src = (ex.get("source_text") or "").strip()
            tgt = (ex.get("target_summary") or "").strip()
            if src and tgt:
                prompt = f"summarize: {src}\n\nsummary:"
                pairs.append((prompt, tgt))
    if qa_path and os.path.exists(qa_path):
        for ex in _load_jsonl(qa_path):
            q = (ex.get("question") or "").strip()
            a = (ex.get("answer") or "").strip()
            if q and a:
                prompt = f"question: {q}\n\nanswer:"
                pairs.append((prompt, a))
    return pairs


def _load_tokenizer(student_dir: str = STUDENT_DIR, fallback_dir: str = TEACHER_DIR):
    """Try to load tokenizer from student dir (merges.txt, vocab.json), else from teacher HF dir."""
    from transformers import AutoTokenizer

    if os.path.exists(os.path.join(student_dir, "vocab.json")) and os.path.exists(os.path.join(student_dir, "merges.txt")):
        # Build a tokenizer from the student files; assume GPT2-like
        try:
            tok = AutoTokenizer.from_pretrained(student_dir, use_fast=True)
            return tok
        except Exception:
            pass
    # Fallback to teacher model tokenizer (expected to be a full HF dir)
    tok = AutoTokenizer.from_pretrained(fallback_dir, use_fast=True)
    return tok


def _load_model(model_dir: str = TEACHER_DIR):
    """Load a HF causal LM from directory (teacher model)."""
    from transformers import AutoModelForCausalLM

    model = AutoModelForCausalLM.from_pretrained(model_dir)
    return model


class SupervisedDataset:
    """
    Tiny dataset wrapper expecting (prompt, target) pairs and a tokenizer.
    It concatenates prompt + target, and creates labels where prompt tokens are ignored (-100)
    so the loss focuses only on the target span.
    """
    def __init__(self, pairs: List[Tuple[str, str]], tokenizer, max_length: int = 1024, max_prompt_length: int = 512):
        self.pairs = pairs
        self.tok = tokenizer
        self.max_length = max_length
        self.max_prompt_length = max_prompt_length

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        prompt, target = self.pairs[idx]
        # Tokenize prompt and target separately to mask prompt in labels
        prompt_ids = self.tok(prompt, truncation=True, max_length=self.max_prompt_length, add_special_tokens=False)["input_ids"]
        target_ids = self.tok(target + self.tok.eos_token, truncation=True, max_length=self.max_length - len(prompt_ids), add_special_tokens=False)["input_ids"]
        input_ids = prompt_ids + target_ids
        attention_mask = [1] * len(input_ids)
        # Mask prompt part in labels with -100
        labels = [-100] * len(prompt_ids) + target_ids.copy()
        return {
            "input_ids": input_ids[: self.max_length],
            "attention_mask": attention_mask[: self.max_length],
            "labels": labels[: self.max_length],
        }


def _collate_fn(features: List[Dict[str, List[int]]], pad_id: int):
    # Simple left padding to the max length in the batch
    max_len = max(len(f["input_ids"]) for f in features)
    batch = {"input_ids": [], "attention_mask": [], "labels": []}
    for f in features:
        pad_len = max_len - len(f["input_ids"])
        batch["input_ids"].append([pad_id] * pad_len + f["input_ids"])
        batch["attention_mask"].append([0] * pad_len + f["attention_mask"])
        # For labels, pad with -100
        batch["labels"].append([-100] * pad_len + f["labels"])
    # Convert to tensors lazily (avoid importing torch at module import)
    import torch

    return {k: torch.tensor(v, dtype=torch.long) for k, v in batch.items()}


def train_from_feedback(
    feedback_json_path: str,
    output_dir: str = DEFAULT_OUTPUT_DIR,
    epochs: int = 1,
    lr: float = 5e-6,
    batch_size: int = 1,
    gradient_accumulation_steps: int = 1,
    max_length: int = 1024,
    max_prompt_length: int = 512,
    model_dir: str = TEACHER_DIR,
    tokenizer_dir_student: str = STUDENT_DIR,
    seed: int = 42,
) -> Dict[str, Any]:
    """
    End-to-end: build datasets from feedback.json, fine-tune HF causal LM, and save the checkpoint.
    Returns a dict with key paths and basic stats.
    """
    os.makedirs(output_dir, exist_ok=True)

    # 1) Ensure datasets exist
    ds_info = build_all_feedback_datasets(feedback_json_path)
    sum_path = ds_info.get("summarization_dataset")
    qa_path = ds_info.get("qa_dataset")

    # 2) Build pairs
    pairs = _prepare_pairs(sum_path, qa_path)
    if not pairs:
        return {
            "ok": False,
            "message": "Aucune donnée d'entraînement issue des feedbacks (JSONL vides ou introuvables).",
            "datasets": ds_info,
        }

    # 3) Load tokenizer & model
    tokenizer = _load_tokenizer(tokenizer_dir_student, fallback_dir=model_dir)
    if tokenizer.pad_token is None:
        # For GPT-like tokenizers, set pad token to eos
        tokenizer.pad_token = tokenizer.eos_token

    model = _load_model(model_dir)

    # 4) Build dataset and Trainer
    train_ds = SupervisedDataset(pairs=pairs, tokenizer=tokenizer, max_length=max_length, max_prompt_length=max_prompt_length)

    from transformers import Trainer, TrainingArguments, default_data_collator

    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=epochs,
        learning_rate=lr,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        logging_steps=10,
        save_steps=0,
        save_total_limit=1,
        report_to=[],  # disable integrations
        remove_unused_columns=False,
        seed=seed,
    )

    collate_fn = (lambda batch: _collate_fn(batch, tokenizer.pad_token_id))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        tokenizer=tokenizer,
        data_collator=collate_fn,
    )

    train_result = trainer.train()

    # 5) Save
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)

    return {
        "ok": True,
        "message": "Fine-tuning terminé",
        "train_samples": len(train_ds),
        "output_dir": output_dir,
        "datasets": ds_info,
        "train_metrics": getattr(train_result, "metrics", {}),
    }


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Fine-tune a HF causal LM from feedback-derived datasets.")
    parser.add_argument("--feedback_json", default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "shared", "feedback.json"), help="Path to feedback.json")
    parser.add_argument("--output_dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--lr", type=float, default=5e-6)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--grad_accum", type=int, default=1)
    parser.add_argument("--max_len", type=int, default=1024)
    parser.add_argument("--max_prompt_len", type=int, default=512)
    parser.add_argument("--model_dir", default=TEACHER_DIR)
    parser.add_argument("--student_tokenizer_dir", default=STUDENT_DIR)

    args = parser.parse_args()

    info = train_from_feedback(
        feedback_json_path=args.feedback_json,
        output_dir=args.output_dir,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        max_length=args.max_len,
        max_prompt_length=args.max_prompt_len,
        model_dir=args.model_dir,
        tokenizer_dir_student=args.student_tokenizer_dir,
    )
    print(json.dumps(info, ensure_ascii=False, indent=2))
